# Copyright (C) 2011 Pierrick Bruneau, see README for full notice

CCP = g++

all: sockclient sockserver

sockclient: sockclient.cpp
	$(CCP) sockclient.cpp -o sockclient

sockserver: sockserver.cpp
	$(CCP) sockserver.cpp -o sockserver

